// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm--B4YUJTE09XrX0hqB6JbHsqDvNzRSs',
    appId: '1:280947535663:web:2c2aa8d9815e3beed0fbda',
    messagingSenderId: '280947535663',
    projectId: 'withme-77c6c',
    authDomain: 'withme-77c6c.firebaseapp.com',
    databaseURL: 'https://withme-77c6c-default-rtdb.firebaseio.com',
    storageBucket: 'withme-77c6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACarjfF_QwYSnxmDw_h4hmiuMXbWq4EEI',
    appId: '1:280947535663:android:1248f3723ac0175ed0fbda',
    messagingSenderId: '280947535663',
    projectId: 'withme-77c6c',
    databaseURL: 'https://withme-77c6c-default-rtdb.firebaseio.com',
    storageBucket: 'withme-77c6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu2rNjlcsdr_-qPmrQ5z18IqWW4JbZ4_A',
    appId: '1:280947535663:ios:29e50fccbcbcc40bd0fbda',
    messagingSenderId: '280947535663',
    projectId: 'withme-77c6c',
    databaseURL: 'https://withme-77c6c-default-rtdb.firebaseio.com',
    storageBucket: 'withme-77c6c.appspot.com',
    iosBundleId: 'com.example.withmeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu2rNjlcsdr_-qPmrQ5z18IqWW4JbZ4_A',
    appId: '1:280947535663:ios:29e50fccbcbcc40bd0fbda',
    messagingSenderId: '280947535663',
    projectId: 'withme-77c6c',
    databaseURL: 'https://withme-77c6c-default-rtdb.firebaseio.com',
    storageBucket: 'withme-77c6c.appspot.com',
    iosBundleId: 'com.example.withmeFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm--B4YUJTE09XrX0hqB6JbHsqDvNzRSs',
    appId: '1:280947535663:web:97986b095e189c16d0fbda',
    messagingSenderId: '280947535663',
    projectId: 'withme-77c6c',
    authDomain: 'withme-77c6c.firebaseapp.com',
    databaseURL: 'https://withme-77c6c-default-rtdb.firebaseio.com',
    storageBucket: 'withme-77c6c.appspot.com',
  );
}
